import csv
from pathlib import Path
from typing import Iterable, List
from .models import Finding


class RunLog:
    def __init__(self) -> None:
        self.findings: List[Finding] = []
        self.suggestions: List[str] = []

    def add(self, finding: Finding) -> None:
        self.findings.append(finding)
        print(f"[{finding.category}] {finding.repo}: {finding.title} -> {finding.action}")

    def suggest(self, repo: str, text: str) -> None:
        if text.strip():
            self.suggestions.append(f"## {repo}\n\n{text.strip()}\n")

    def export_csv(self, path: str | Path) -> None:
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        fields = list(Finding.now("", "", "", "", "").row().keys())
        with path.open("w", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(f, fieldnames=fields)
            writer.writeheader()
            for item in self.findings:
                writer.writerow(item.row())

    def export_suggestions(self, path: str | Path) -> None:
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        body = "# Nova Suggestions\n\n"
        body += "Generated by Nova Repo Maintainer Agent. Review before implementing.\n\n"
        body += "\n".join(self.suggestions) if self.suggestions else "No suggestions generated.\n"
        path.write_text(body, encoding="utf-8")
