from __future__ import annotations
import csv
from pathlib import Path
from .models import Finding

class RunLog:
    def __init__(self):
        self.rows = []
        self.suggestions = []

    def add(self, finding: Finding):
        self.rows.append(finding)
        print(f"[{finding.kind}] {finding.repo}: {finding.title} -> {finding.action}")

    def suggest(self, repo: str, text: str | None):
        text = (text or "").strip()
        if text:
            self.suggestions.append((repo, text))

    def export_csv(self, path):
        path = Path(path)
        fields = ["timestamp","owner","repo","kind","severity","title","action","state","url","details"]
        with path.open("w", newline="", encoding="utf-8") as f:
            w = csv.DictWriter(f, fieldnames=fields)
            w.writeheader()
            for row in self.rows:
                w.writerow(row.to_dict())

    def export_suggestions(self, path):
        path = Path(path)
        with path.open("w", encoding="utf-8") as f:
            f.write("# Nova Suggestions\n\nGenerated by Nova Repo Maintainer Agent. Review before implementing.\n\n")
            if not self.suggestions:
                f.write("No suggestions generated.\n")
            for repo, text in self.suggestions:
                f.write(f"## {repo}\n\n{text.strip()}\n\n")
